"""Question templates for seed data.

Each bank has ~10 base templates. The seed script cycles through
them to reach 20 questions per bank.
"""

JS_QUESTIONS = [
    {
        "type": "SINGLE",
        "content": "JavaScript中 typeof null 的结果是？",
        "options": ["A. null", "B. undefined", "C. object", "D. number"],
        "answer": "C",
        "explanation": "这是JavaScript的历史遗留bug。在JS最初的实现中，值的类型标签存储在低位，null的类型标签全为0，与object相同。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "类型"],
    },
    {
        "type": "SINGLE",
        "content": "以下哪个不是 JavaScript 的基本数据类型？",
        "options": ["A. string", "B. number", "C. array", "D. boolean"],
        "answer": "C",
        "explanation": "JavaScript有7种基本数据类型：string, number, boolean, null, undefined, symbol, bigint。array是引用类型（object）。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "类型"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些是ES6新增的特性？",
        "options": ["A. let/const", "B. 箭头函数", "C. Promise", "D. class语法"],
        "answer": "ABCD",
        "explanation": "ES6（ES2015）引入了let/const块级作用域、箭头函数、Promise、class语法糖、模板字符串、解构赋值等大量新特性。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "ES6"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "在JavaScript中，0.1 + 0.2 === 0.3 的结果是 true。",
        "options": ["正确", "错误"],
        "answer": "错误",
        "explanation": "由于浮点数精度问题，0.1 + 0.2 = 0.30000000000000004，不等于0.3。",
        "difficulty": "MEDIUM",
        "tags": ["JavaScript", "浮点数"],
    },
    {
        "type": "SINGLE",
        "content": "下面代码的输出是什么？\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100);\n}",
        "options": ["A. 0 1 2", "B. 3 3 3", "C. undefined undefined undefined", "D. 报错"],
        "answer": "B",
        "explanation": "var声明的变量没有块级作用域，循环结束后i=3。使用let可以解决此问题。",
        "difficulty": "MEDIUM",
        "tags": ["JavaScript", "闭包", "事件循环"],
    },
    {
        "type": "SINGLE",
        "content": "Promise对象的状态不包括以下哪个？",
        "options": ["A. pending", "B. fulfilled", "C. rejected", "D. completed"],
        "answer": "D",
        "explanation": "Promise只有三种状态：pending（进行中）、fulfilled（已成功）、rejected（已失败）。没有completed状态。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "Promise"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些方法可以创建数组？",
        "options": ["A. new Array()", "B. []", "C. Array.from()", "D. Array.of()"],
        "answer": "ABCD",
        "explanation": "以上四种方式都可以创建数组。new Array()和[]是基础语法，Array.from()从类数组创建，Array.of()从参数创建。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "数组"],
    },
    {
        "type": "SINGLE",
        "content": "async/await 是基于什么实现的语法糖？",
        "options": ["A. Generator", "B. Promise", "C. Callback", "D. EventEmitter"],
        "answer": "B",
        "explanation": "async/await 是 Promise 的语法糖，使异步代码看起来像同步代码。async函数始终返回一个Promise。",
        "difficulty": "MEDIUM",
        "tags": ["JavaScript", "异步"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "在严格模式('use strict')下，未声明的变量赋值会抛出ReferenceError。",
        "options": ["正确", "错误"],
        "answer": "正确",
        "explanation": "严格模式下，给未声明的变量赋值会抛出ReferenceError，而普通模式下会创建一个全局变量。",
        "difficulty": "EASY",
        "tags": ["JavaScript", "严格模式"],
    },
    {
        "type": "SINGLE",
        "content": "以下哪种方式可以阻止事件冒泡？",
        "options": ["A. event.preventDefault()", "B. event.stopPropagation()", "C. event.stopBubble()", "D. event.cancelBubble()"],
        "answer": "B",
        "explanation": "event.stopPropagation()用于阻止事件冒泡。preventDefault()阻止默认行为，cancelBubble是IE旧属性。",
        "difficulty": "MEDIUM",
        "tags": ["JavaScript", "DOM", "事件"],
    },
]

ALGO_QUESTIONS = [
    {
        "type": "SINGLE",
        "content": "以下哪种排序算法的平均时间复杂度是O(n log n)？",
        "options": ["A. 冒泡排序", "B. 归并排序", "C. 插入排序", "D. 选择排序"],
        "answer": "B",
        "explanation": "归并排序的平均时间复杂度为O(n log n)。冒泡、插入、选择排序均为O(n²)。",
        "difficulty": "EASY",
        "tags": ["算法", "排序"],
    },
    {
        "type": "SINGLE",
        "content": "二分查找的前提条件是？",
        "options": ["A. 数据有序", "B. 数据存储在链表中", "C. 数据量小于100", "D. 数据无序"],
        "answer": "A",
        "explanation": "二分查找要求数据有序（升序或降序），通过不断将查找区间减半来快速定位目标值。",
        "difficulty": "EASY",
        "tags": ["算法", "查找"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些属于动态规划的特征？",
        "options": ["A. 最优子结构", "B. 重叠子问题", "C. 贪心选择", "D. 状态转移方程"],
        "answer": "ABD",
        "explanation": "动态规划的特征包括最优子结构、重叠子问题和状态转移方程。贪心选择是贪心算法的特征。",
        "difficulty": "MEDIUM",
        "tags": ["算法", "动态规划"],
    },
    {
        "type": "SINGLE",
        "content": "栈(Stack)的特点是？",
        "options": ["A. 先进先出", "B. 先进后出", "C. 随机访问", "D. 按优先级出队"],
        "answer": "B",
        "explanation": "栈是后进先出（LIFO）的数据结构。队列是先入先出（FIFO）。",
        "difficulty": "EASY",
        "tags": ["数据结构", "栈"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "哈希表(Hash Table)的查找操作在最坏情况下的时间复杂度为O(1)。",
        "options": ["正确", "错误"],
        "answer": "错误",
        "explanation": "哈希表最坏情况下（所有key都冲突），查找时间复杂度退化为O(n)。平均情况下才是O(1)。",
        "difficulty": "MEDIUM",
        "tags": ["数据结构", "哈希表"],
    },
    {
        "type": "SINGLE",
        "content": "深度优先搜索(DFS)通常使用什么数据结构实现？",
        "options": ["A. 队列", "B. 栈", "C. 堆", "D. 链表"],
        "answer": "B",
        "explanation": "DFS通常使用栈（递归调用栈或显式栈）实现。BFS（广度优先搜索）使用队列。",
        "difficulty": "EASY",
        "tags": ["算法", "图", "搜索"],
    },
    {
        "type": "SINGLE",
        "content": "一个含n个节点的完全二叉树，其高度大约是多少？",
        "options": ["A. n", "B. n²", "C. log n", "D. 2^n"],
        "answer": "C",
        "explanation": "完全二叉树的高度约为log₂n。这也是为什么二叉搜索树在平衡时查找效率为O(log n)。",
        "difficulty": "MEDIUM",
        "tags": ["数据结构", "树"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些算法可以用来求解最短路径？",
        "options": ["A. Dijkstra算法", "B. Floyd-Warshall算法", "C. Kruskal算法", "D. Bellman-Ford算法"],
        "answer": "ABD",
        "explanation": "Dijkstra（单源非负权）、Floyd-Warshall（多源）、Bellman-Ford（单源可负权）都是最短路径算法。Kruskal是最小生成树算法。",
        "difficulty": "HARD",
        "tags": ["算法", "图", "最短路径"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "快速排序在最坏情况下的时间复杂度是O(n²)。",
        "options": ["正确", "错误"],
        "answer": "正确",
        "explanation": "快速排序在每次选择的pivot都是最小/最大值时（如已排序数组），会退化为O(n²)。但平均情况下为O(n log n)。",
        "difficulty": "MEDIUM",
        "tags": ["算法", "排序"],
    },
    {
        "type": "SINGLE",
        "content": "LRU缓存淘汰策略中，LRU代表什么？",
        "options": ["A. Last Recently Used", "B. Least Recently Used", "C. Latest Replaced Unit", "D. Low Resource Usage"],
        "answer": "B",
        "explanation": "LRU = Least Recently Used（最近最少使用），淘汰最长时间未被访问的数据。常用哈希表+双向链表实现。",
        "difficulty": "EASY",
        "tags": ["算法", "缓存"],
    },
]

NETWORK_QUESTIONS = [
    {
        "type": "SINGLE",
        "content": "HTTP协议的默认端口号是？",
        "options": ["A. 21", "B. 80", "C. 443", "D. 8080"],
        "answer": "B",
        "explanation": "HTTP默认端口80，HTTPS默认端口443，FTP默认端口21。",
        "difficulty": "EASY",
        "tags": ["网络", "HTTP"],
    },
    {
        "type": "SINGLE",
        "content": "TCP三次握手中，客户端首先发送什么？",
        "options": ["A. ACK", "B. FIN", "C. SYN", "D. RST"],
        "answer": "C",
        "explanation": "三次握手过程：1)客户端→SYN→服务器 2)服务器→SYN+ACK→客户端 3)客户端→ACK→服务器。",
        "difficulty": "EASY",
        "tags": ["网络", "TCP"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些是HTTP的请求方法？",
        "options": ["A. GET", "B. POST", "C. SEND", "D. DELETE"],
        "answer": "ABD",
        "explanation": "GET、POST、DELETE都是标准HTTP方法，还有PUT、PATCH、HEAD、OPTIONS等。SEND不是HTTP方法。",
        "difficulty": "EASY",
        "tags": ["网络", "HTTP"],
    },
    {
        "type": "SINGLE",
        "content": "DNS的主要功能是？",
        "options": ["A. 加密通信", "B. 域名解析为IP地址", "C. 分配IP地址", "D. 防火墙过滤"],
        "answer": "B",
        "explanation": "DNS（Domain Name System）将域名（如www.example.com）解析为IP地址。",
        "difficulty": "EASY",
        "tags": ["网络", "DNS"],
    },
    {
        "type": "SINGLE",
        "content": "OSI七层模型中，传输层是哪一层？",
        "options": ["A. 第2层", "B. 第3层", "C. 第4层", "D. 第5层"],
        "answer": "C",
        "explanation": "OSI七层模型：物理层(1)、数据链路层(2)、网络层(3)、传输层(4)、会话层(5)、表示层(6)、应用层(7)。TCP/UDP工作在传输层。",
        "difficulty": "MEDIUM",
        "tags": ["网络", "OSI"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "UDP是一种面向连接的、可靠的传输协议。",
        "options": ["正确", "错误"],
        "answer": "错误",
        "explanation": "UDP是无连接的、不可靠的传输协议。TCP才是面向连接的、可靠的协议。",
        "difficulty": "EASY",
        "tags": ["网络", "UDP", "TCP"],
    },
    {
        "type": "SINGLE",
        "content": "HTTP状态码 404 表示什么？",
        "options": ["A. 服务器内部错误", "B. 资源未找到", "C. 重定向", "D. 请求成功"],
        "answer": "B",
        "explanation": "404 Not Found表示请求的资源不存在。500是服务器内部错误，301/302是重定向，200是成功。",
        "difficulty": "EASY",
        "tags": ["网络", "HTTP"],
    },
    {
        "type": "MULTIPLE",
        "content": "以下哪些属于应用层协议？",
        "options": ["A. HTTP", "B. TCP", "C. SMTP", "D. IP"],
        "answer": "AC",
        "explanation": "HTTP和SMTP都是应用层协议。TCP是传输层协议，IP是网络层协议。",
        "difficulty": "MEDIUM",
        "tags": ["网络", "协议"],
    },
    {
        "type": "SINGLE",
        "content": "Cookie和Session的区别，以下说法正确的是？",
        "options": ["A. Cookie存储在服务器，Session存储在客户端", "B. Cookie存储在客户端，Session存储在服务器", "C. 两者都存储在服务器", "D. 两者都存储在客户端"],
        "answer": "B",
        "explanation": "Cookie存储在客户端浏览器，Session存储在服务器端。Cookie大小有限制（约4KB），Session相对更安全。",
        "difficulty": "MEDIUM",
        "tags": ["网络", "Cookie", "Session"],
    },
    {
        "type": "TRUE_FALSE",
        "content": "HTTPS通过在HTTP和TCP之间加入SSL/TLS层来保证通信安全。",
        "options": ["正确", "错误"],
        "answer": "正确",
        "explanation": "HTTPS = HTTP + SSL/TLS。TLS握手后进行加密通信，提供数据加密、身份认证和数据完整性保护。",
        "difficulty": "EASY",
        "tags": ["网络", "HTTPS", "安全"],
    },
]
